Repository SparkPost/2web2ui, pull requests merged in 2019-06, with the labels that each got.

#1061 TR-1445 Create Templates
  src/config/routes/templates.js
  src/helpers/string.js
  src/helpers/tests/string.test.js
  src/pages/templates/components/FromEmailWrapper.js
  src/pages/templates/components/validation.js
  src/pages/templatesV2/CreatePage.container.js
  src/pages/templatesV2/CreatePage.js
  src/pages/templatesV2/CreatePage.module.scss
  src/pages/templatesV2/ListPage.js
  src/pages/templatesV2/components/FromEmail.js
  src/pages/templatesV2/components/FromEmail.module.scss
  src/pages/templatesV2/components/FromEmailInput.js
  src/pages/templatesV2/components/FromEmailMenu.js
  src/pages/templatesV2/components/FromEmailWrapper.js
  src/pages/templatesV2/components/create/CreateForm.js
  src/pages/templatesV2/components/create/tests/CreateForm.test.js
  src/pages/templatesV2/components/create/tests/__snapshots__/CreateForm.test.js.snap
  src/pages/templatesV2/components/tests/FromEmail.test.js
  src/pages/templatesV2/components/tests/FromEmailInput.test.js
  src/pages/templatesV2/components/tests/FromEmailMenu.test.js
  src/pages/templatesV2/components/tests/FromEmailWrapper.test.js
  src/pages/templatesV2/components/tests/__snapshots__/FromEmailInput.test.js.snap
  src/pages/templatesV2/components/tests/__snapshots__/FromEmailMenu.test.js.snap
  src/pages/templatesV2/components/tests/__snapshots__/FromEmailWrapper.test.js.snap
  src/pages/templatesV2/components/tests/validation.test.js
  src/pages/templatesV2/components/validation.js
  src/pages/templatesV2/index.js
  src/pages/templatesV2/tests/CreatePage.test.js
  src/pages/templatesV2/tests/__snapshots__/CreatePage.test.js.snap
  src/pages/templatesV2/tests/__snapshots__/ListPage.test.js.snap
  src/selectors/templates.js
  src/selectors/tests/templates.test.js
Labels: TemplateV2

#1062 TR-1470 - Makes the second top panel fixed
  src/pages/templatesV2/EditAndPreview.module.scss
  src/pages/templatesV2/EditAndPreviewPage.js
  src/pages/templatesV2/tests/__snapshots__/EditAndPreviewPage.test.js.snap
Labels: :eyes: needs review, TemplateV2

#1066 TR-1348 Template Settings
  src/components/toggleBlock/ToggleBlock.js
  src/components/toggleBlock/tests/__snapshots__/ToggleBlock.test.js.snap
  src/pages/templatesV2/EditAndPreviewPage.container.js
  src/pages/templatesV2/EditAndPreviewPage.js
  src/pages/templatesV2/components/DeleteTemplate.js
  src/pages/templatesV2/components/settings/EditSettings.js
  src/pages/templatesV2/components/settings/EditSettings.module.scss
  src/pages/templatesV2/components/settings/Form.Container.js
  src/pages/templatesV2/components/settings/Form.js
  src/pages/templatesV2/components/settings/Form.module.scss
  src/pages/templatesV2/components/settings/SettingsSection.js
  src/pages/templatesV2/components/settings/SettingsSection.module.scss
  src/pages/templatesV2/components/settings/tests/EditSettings.test.js
  src/pages/templatesV2/components/settings/tests/Form.test.js
  src/pages/templatesV2/components/settings/tests/SettignsSection.test.js
  src/pages/templatesV2/components/settings/tests/__snapshots__/EditSettings.test.js.snap
  src/pages/templatesV2/components/settings/tests/__snapshots__/Form.test.js.snap
  src/pages/templatesV2/components/settings/tests/__snapshots__/SettignsSection.test.js.snap
  src/pages/templatesV2/components/tests/DeleteTemplate.test.js
  src/pages/templatesV2/components/tests/EditNavigation.test.js
  src/pages/templatesV2/components/tests/__snapshots__/DeleteTemplate.test.js.snap
  src/pages/templatesV2/components/tests/__snapshots__/EditNavigation.test.js.snap
  src/pages/templatesV2/constants/editNavigationLinks.js
  src/pages/templatesV2/context/EditorContext.js
  src/pages/templatesV2/context/tests/EditorContext.test.js
  src/pages/templatesV2/hooks/tests/useEditorNavigation.test.js
  src/pages/templatesV2/hooks/useEditorNavigation.js
Labels: TemplateV2

#1060 TR-1373 Editor actions
  package-lock.json
  package.json
  src/actions/templates.js
  src/actions/tests/__snapshots__/templates.test.js.snap
  src/pages/templatesV2/EditAndPreviewPage.container.js
  src/pages/templatesV2/EditAndPreviewPage.js
  src/pages/templatesV2/EditAndPreviewPage.module.scss
  src/pages/templatesV2/components/EditContentsPrimaryArea.js
  src/pages/templatesV2/components/editorActions/Actions.module.scss
  src/pages/templatesV2/components/editorActions/DraftModeActions.js
  src/pages/templatesV2/components/editorActions/EditDraft.js
  src/pages/templatesV2/components/editorActions/PublishedModeActions.js
  src/pages/templatesV2/components/editorActions/SaveAndPublish.js
  src/pages/templatesV2/components/editorActions/SaveDraft.js
  src/pages/templatesV2/components/editorActions/ViewPublished.js
  src/pages/templatesV2/components/editorActions/tests/DraftModeActions.test.js
  src/pages/templatesV2/components/editorActions/tests/EditDraft.test.js
  src/pages/templatesV2/components/editorActions/tests/PublishedModeActions.test.js
  src/pages/templatesV2/components/editorActions/tests/SaveAndPublish.test.js
  src/pages/templatesV2/components/editorActions/tests/SaveDraft.test.js
  src/pages/templatesV2/components/editorActions/tests/ViewPublished.test.js
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/DraftModeActions.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/EditDraft.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/PublishedModeActions.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/SaveAndPublish.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/SaveDraft.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/ViewPublished.test.js.snap
  src/pages/templatesV2/components/tests/EditContentsPrimaryArea.test.js
  src/pages/templatesV2/components/tests/EditNavigation.test.js
  src/pages/templatesV2/components/tests/__snapshots__/EditContentsPrimaryArea.test.js.snap
  src/pages/templatesV2/components/tests/__snapshots__/EditNavigation.test.js.snap
  src/pages/templatesV2/constants/editNavigationLinks.js
  src/pages/templatesV2/context/EditorContext.js
  src/reducers/templates.js
  src/reducers/tests/templates.test.js
Labels: :eyes: needs review, TemplateV2

#1068 TR-1533 Fix content editing modes
  src/config/routes/templates.js
  src/pages/templatesV2/CreatePage.js
  src/pages/templatesV2/EditAndPreviewPage.container.js
  src/pages/templatesV2/EditAndPreviewPage.js
  src/pages/templatesV2/EditAndPreviewPage.module.scss
  src/pages/templatesV2/ListPage.js
  src/pages/templatesV2/components/EditAmpSection.js
  src/pages/templatesV2/components/EditHtmlSection.js
  src/pages/templatesV2/components/EditTextSection.js
  src/pages/templatesV2/components/ListComponents.js
  src/pages/templatesV2/components/editorActions/Actions.module.scss
  src/pages/templatesV2/components/editorActions/DraftModeActions.js
  src/pages/templatesV2/components/editorActions/EditDraft.js
  src/pages/templatesV2/components/editorActions/PublishedModeActions.js
  src/pages/templatesV2/components/editorActions/SaveAndPublish.js
  src/pages/templatesV2/components/editorActions/SaveDraft.js
  src/pages/templatesV2/components/editorActions/ViewPublished.js
  src/pages/templatesV2/components/editorActions/tests/DraftModeActions.test.js
  src/pages/templatesV2/components/editorActions/tests/EditDraft.test.js
  src/pages/templatesV2/components/editorActions/tests/PublishedModeActions.test.js
  src/pages/templatesV2/components/editorActions/tests/SaveAndPublish.test.js
  src/pages/templatesV2/components/editorActions/tests/ViewPublished.test.js
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/DraftModeActions.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/EditDraft.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/PublishedModeActions.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/SaveAndPublish.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/SaveDraft.test.js.snap
  src/pages/templatesV2/components/editorActions/tests/__snapshots__/ViewPublished.test.js.snap
  src/pages/templatesV2/components/settings/Form.Container.js
  src/pages/templatesV2/components/settings/Form.js
  src/pages/templatesV2/components/settings/Form.module.scss
  src/pages/templatesV2/components/settings/tests/Form.test.js
  src/pages/templatesV2/components/settings/tests/__snapshots__/Form.test.js.snap
  src/pages/templatesV2/components/tests/EditAmpSection.test.js
  src/pages/templatesV2/components/tests/EditHtmlSection.test.js
  src/pages/templatesV2/components/tests/EditTextSection.test.js
  src/pages/templatesV2/components/tests/ListComponents.test.js
  src/pages/templatesV2/components/tests/__snapshots__/ListComponents.test.js.snap
  src/pages/templatesV2/context/EditorContext.js
  src/pages/templatesV2/hooks/tests/useEditorContent.test.js
  src/pages/templatesV2/hooks/tests/useEditorNavigation.test.js
  src/pages/templatesV2/hooks/useEditorContent.js
  src/pages/templatesV2/hooks/useEditorNavigation.js
  src/pages/templatesV2/tests/CreatePage.test.js
  src/pages/templatesV2/tests/EditAndPreviewPage.test.js
  src/pages/templatesV2/tests/__snapshots__/EditAndPreviewPage.test.js.snap
  src/pages/templatesV2/tests/__snapshots__/ListPage.test.js.snap
  src/selectors/templates.js
  src/selectors/tests/__snapshots__/templates.test.js.snap
Labels: TemplateV2

#1034 TR-1282: Lint AMP HTML in prototype fullscreen code editor
  src/pages/templatesV2/components/EditAmpSection.js
  src/pages/templatesV2/components/Editor.js
  src/pages/templatesV2/components/Editor.module.scss
  src/pages/templatesV2/components/tests/EditAmpSection.test.js
  src/pages/templatesV2/components/tests/Editor.test.js
  src/pages/templatesV2/components/tests/__snapshots__/EditAmpSection.test.js.snap
  src/pages/templatesV2/components/tests/__snapshots__/Editor.test.js.snap
  src/pages/templatesV2/context/EditorContext.js
  src/pages/templatesV2/context/tests/__snapshots__/EditorContext.test.js.snap
  src/pages/templatesV2/hooks/tests/useEditor.test.js
  src/pages/templatesV2/hooks/tests/useEditorAnnotations.test.js
  src/pages/templatesV2/hooks/useEditor.js
  src/pages/templatesV2/hooks/useEditorAnnotations.js
  third/ampValidator/index.js
  third/ampValidator/validator.js
  third/readme.md
Labels: TemplateV2, enhancement

#1081 TR-1560 Update editor nav item labels
  src/pages/templatesV2/EditAndPreviewPage.module.scss
  src/pages/templatesV2/components/tests/EditNavigation.test.js
  src/pages/templatesV2/components/tests/__snapshots__/EditNavigation.test.js.snap
  src/pages/templatesV2/constants/editNavigationLinks.js
  src/pages/templatesV2/hooks/useEditorContent.js
Labels: TemplateV2
